# Generated by Django 4.2.5 on 2023-10-29 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=60, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=60, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=60, verbose_name="Отчество"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужчина"), ("Ж", "Женщина")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "passport_series",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_series",
                                message="Field must consist of exactly four digits.",
                                regex="^\\d{4}$",
                            )
                        ],
                        verbose_name="Серия",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_number",
                                message="Field must consist of exactly six digits.",
                                regex="^\\d{6}$",
                            )
                        ],
                        verbose_name="Номер",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_number",
                                message="Field must consist of exactly six digits.",
                                regex="^\\d{3}-\\d{3}$",
                            )
                        ],
                        verbose_name="Код подразделения",
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(max_length=60, verbose_name="Кем выдан"),
                ),
                ("date_of_issued", models.DateField(verbose_name="Дата выдачи")),
                (
                    "registration_address",
                    models.CharField(max_length=60, verbose_name="Адрес регистрации"),
                ),
                (
                    "address",
                    models.CharField(max_length=60, verbose_name="Фактический адрес"),
                ),
                (
                    "place_of_birth",
                    models.CharField(max_length=60, verbose_name="Место рождения"),
                ),
                (
                    "taxpayer_identification_number",
                    models.IntegerField(verbose_name="ИНН"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Почта"
                    ),
                ),
                (
                    "bank_of_recipient",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Банк получатель",
                    ),
                ),
                (
                    "bik_bank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="БИК Банк"
                    ),
                ),
                (
                    "inn_bank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ИНН Банк"
                    ),
                ),
                (
                    "kpp_bank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="КПП Банк"
                    ),
                ),
                (
                    "krr_bank",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Корр. Счет"
                    ),
                ),
                (
                    "recipient_account",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Счет Получателя"
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeasingItemModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60, verbose_name="Навзвание")),
                (
                    "pts",
                    models.CharField(
                        max_length=20,
                        verbose_name="Паспорт транспортного средства (ПТС)",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        max_length=20, verbose_name="Идентификационный номер (VIN)"
                    ),
                ),
                (
                    "vehicle_model_ts",
                    models.CharField(max_length=20, verbose_name="Марка, модель ТС"),
                ),
                (
                    "year_of_vehicle_manufacture_ts",
                    models.DateField(verbose_name="Год изготовления ТС"),
                ),
                (
                    "engine_model",
                    models.CharField(max_length=60, verbose_name="Модель, № двигателя"),
                ),
                (
                    "chassis",
                    models.CharField(max_length=20, verbose_name="Шасси (рама) №"),
                ),
                (
                    "body",
                    models.CharField(
                        max_length=20, verbose_name="Кузов (кабина, прицеп) №"
                    ),
                ),
                (
                    "body_color",
                    models.CharField(
                        max_length=20, verbose_name="Цвет кузова (кабины, прицепа)"
                    ),
                ),
                (
                    "issued_passport_organization",
                    models.CharField(
                        max_length=60,
                        verbose_name="Наименование организации, выдавшей паспорт",
                    ),
                ),
                (
                    "passport_issue_date",
                    models.DateField(verbose_name="Дата выдачи паспорта"),
                ),
                (
                    "registration_certificate",
                    models.CharField(
                        max_length=60,
                        verbose_name="Свидетельство о регистрации ТС (СТС)",
                    ),
                ),
                (
                    "register_sign",
                    models.CharField(
                        max_length=20, verbose_name="Регистрационный знак"
                    ),
                ),
                ("mileage", models.PositiveIntegerField(verbose_name="Пробег")),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Цена автомобиля"
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeasingAgreementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_date", models.DateField(verbose_name="Дата договора")),
                (
                    "client_fio",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Фио Клиента"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Сумма договора")),
                (
                    "agreement_term",
                    models.PositiveIntegerField(
                        choices=[(12, "12 мес"), (18, "18 мес"), (24, "24 мес")],
                        verbose_name="Срок договора",
                    ),
                ),
                (
                    "payment_schedule",
                    models.CharField(
                        choices=[
                            ("Гибрид", "Гибрид"),
                            ("Аннуитет", "Аннуитет"),
                            ("Градиент", "Градиент"),
                            ("Проценты", "Проценты"),
                            ("Стандарт", "Стандарт"),
                        ],
                        max_length=20,
                        verbose_name="График платежей",
                    ),
                ),
                (
                    "interest_rate",
                    models.IntegerField(verbose_name="Процентная ставка"),
                ),
                (
                    "moratorium",
                    models.CharField(max_length=20, verbose_name="Мораторий"),
                ),
                (
                    "payment_split_checkbox",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Галочка разделения платежа"
                    ),
                ),
                (
                    "transfer_amount_via_RS",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма перевода через РС"
                    ),
                ),
                (
                    "cash_withdrawal_amount_DS",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма выдачи наличными ДС"
                    ),
                ),
                ("status", models.BooleanField(blank=True, default=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="api.clientmodel",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "leasing_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item",
                        to="api.leasingitemmodel",
                        verbose_name="Предмет лизинга",
                    ),
                ),
            ],
        ),
    ]
