# Generated by Django 4.2.5 on 2023-10-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="taxpayer_identification_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ИНН"
            ),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="agreement_term",
            field=models.PositiveIntegerField(
                choices=[(12, "12 мес"), (24, "18 мес"), (36, "24 мес")],
                verbose_name="Срок договора",
            ),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="api.clientmodel",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="leasing_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="api.leasingitemmodel",
                verbose_name="Предмет лизинга",
            ),
        ),
    ]
