# Generated by Django 4.2.5 on 2023-11-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_clientmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="moratorium",
            field=models.PositiveIntegerField(verbose_name="Мораторий"),
        ),
    ]
