# Generated by Django 4.2.5 on 2023-11-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_leasingagreementmodel_moratorium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='leasingagreementmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='leasingitemmodel',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='leasingagreementmodel',
            name='interest_rate',
            field=models.FloatField(verbose_name='Процентная ставка'),
        ),
    ]
