# Generated by Django 4.2.5 on 2023-11-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_leasingagreementmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Сумма договора"),
        ),
    ]
