# Generated by Django 4.2.5 on 2023-11-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_clientmodel_bik_bank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasingagreementmodel",
            name="payment",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Платеж"
            ),
        ),
    ]
