# Generated by Django 4.2.5 on 2023-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_leasingagreementmodel_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="bank_of_recipient",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Банк получатель"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="bik_bank",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="БИК Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="email",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Почта"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="inn_bank",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="ИНН Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="kpp_bank",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="КПП Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="krr_bank",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Корр. Счет"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="name",
            field=models.CharField(max_length=1000, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="patronymic",
            field=models.CharField(max_length=1000, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="place_of_birth",
            field=models.TextField(max_length=1000, verbose_name="Место рождения"),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="recipient_account",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Счет Получателя"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="surname",
            field=models.CharField(max_length=1000, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="agreement_term",
            field=models.PositiveIntegerField(
                choices=[(12, "12 мес"), (24, "24 мес"), (36, "36 мес")],
                verbose_name="Срок договора",
            ),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="client_fio",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Фио Клиента"
            ),
        ),
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="payment_schedule",
            field=models.CharField(
                choices=[
                    ("Гибрид", "Гибрид"),
                    ("Аннуитет", "Аннуитет"),
                    ("Градиент", "Градиент"),
                    ("Проценты", "Проценты"),
                    ("Стандарт", "Стандарт"),
                ],
                max_length=1000,
                verbose_name="График платежей",
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="body",
            field=models.CharField(
                max_length=1000, verbose_name="Кузов (кабина, прицеп) №"
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="chassis",
            field=models.CharField(max_length=1000, verbose_name="Шасси (рама) №"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="engine_model",
            field=models.CharField(max_length=1000, verbose_name="Модель, № двигателя"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="pts",
            field=models.CharField(
                max_length=1000, verbose_name="Паспорт транспортного средства (ПТС)"
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="register_sign",
            field=models.CharField(
                max_length=1000, verbose_name="Регистрационный знак"
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="vin",
            field=models.CharField(
                max_length=1000, verbose_name="Идентификационный номер (VIN)"
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="year_of_vehicle_manufacture_ts",
            field=models.PositiveIntegerField(verbose_name="Год изготовления ТС"),
        ),
    ]
