# Generated by Django 4.2.5 on 2023-11-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_leasingitemmodel_year_of_vehicle_manufacture_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosingLeasingModel",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "date_of_closing",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрытия договора"
                    ),
                ),
                (
                    "total_closing_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма закрытия договора"
                    ),
                ),
            ],
        ),
    ]
