# Generated by Django 4.2.5 on 2023-11-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_closingleasingmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="payment",
            field=models.FloatField(blank=True, null=True, verbose_name="Платеж"),
        ),
    ]
