# Generated by Django 4.2.5 on 2024-12-25 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_leasingagreementmodel_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='address_principal',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Фактический адрес доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='date_of_birth_principal',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='date_of_issued_principal',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='date_proxy',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата доверенности'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='department_code_principal',
            field=models.CharField(blank=True, default='', max_length=7, null=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Field must consist of exactly six digits.', regex='^\\d{3}-\\d{3}$')], verbose_name='Код подразделения доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='fio_notary',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Фио нотариуса'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='fio_principal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='ФИО Доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='issued_by_principal',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Кем выдан доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='number_proxy',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Номер доверенности'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='passport_number_principal',
            field=models.CharField(blank=True, default='', max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Field must consist of exactly six digits.', regex='^\\d{6}$')], verbose_name='Номер паспорта доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='passport_series_principal',
            field=models.CharField(blank=True, default='', max_length=4, null=True, validators=[django.core.validators.RegexValidator(code='invalid_series', message='Field must consist of exactly four digits.', regex='^\\d{4}$')], verbose_name='Серия паспорта доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='place_of_birth_principal',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Место рождения доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='registry_number',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Номер в реестре'),
        ),
    ]
