# Generated by Django 4.2.5 on 2024-12-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_clientmodel_fio_principal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='date_of_birth_principal',
            new_name='date_of_birthAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='date_of_issued_principal',
            new_name='date_of_issuedAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='date_proxy',
            new_name='date_of_issued_of_attorneyAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='department_code_principal',
            new_name='department_codeAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='gender_principal',
            new_name='genderAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='issued_by_principal',
            new_name='issued_byAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='name_principal',
            new_name='nameAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='fio_notary',
            new_name='notary_full_nameAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='number_proxy',
            new_name='number_formAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='registry_number',
            new_name='number_registryAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='passport_number_principal',
            new_name='passport_numberAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='passport_series_principal',
            new_name='passport_seriesAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='patronymic_principal',
            new_name='patronymicAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='place_of_birth_principal',
            new_name='place_of_birthAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='address_principal',
            new_name='registration_addressAdditionally',
        ),
        migrations.RenameField(
            model_name='clientmodel',
            old_name='surname_principal',
            new_name='surnameAdditionally',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='is_principal',
        ),
    ]
