# Generated by Django 4.2.5 on 2023-10-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_clientmodel_taxpayer_identification_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leasingagreementmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leasingitemmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="leasingagreementmodel",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="leasingitemmodel",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
