# Generated by Django 4.2.5 on 2023-11-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clientmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingagreementmodel',
            name='price',
            field=models.FloatField(verbose_name='Сумма договора'),
        ),
    ]
