# Generated by Django 4.2.5 on 2023-11-04 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_leasingagreementmodel_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasingagreementmodel",
            name="moratorium",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Мораторий",
            ),
        ),
    ]
