# Generated by Django 4.2.5 on 2023-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_leasingagreementmodel_moratorium"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="address",
            field=models.TextField(verbose_name="Фактический адрес"),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="issued_by",
            field=models.TextField(verbose_name="Кем выдан"),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="registration_address",
            field=models.TextField(verbose_name="Адрес регистрации"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="body_color",
            field=models.TextField(verbose_name="Цвет кузова (кабины, прицепа)"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="issued_passport_organization",
            field=models.TextField(
                verbose_name="Наименование организации, выдавшей паспорт"
            ),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="registration_certificate",
            field=models.TextField(verbose_name="Свидетельство о регистрации ТС (СТС)"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="title",
            field=models.TextField(verbose_name="Навзвание"),
        ),
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="vehicle_model_ts",
            field=models.TextField(verbose_name="Марка, модель ТС"),
        ),
    ]
