# Generated by Django 4.2.5 on 2023-11-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_clientmodel_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="bik_bank",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="БИК Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="inn_bank",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="ИНН Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="kpp_bank",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="КПП Банк"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="krr_bank",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Корр. Счет"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="recipient_account",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="Счет Получателя"
            ),
        ),
    ]
