# Generated by Django 4.2.5 on 2023-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_clientmodel_bank_of_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasingitemmodel",
            name="year_of_vehicle_manufacture_ts",
            field=models.DateField(verbose_name="Год изготовления ТС"),
        ),
    ]
