# Generated by Django 4.2.5 on 2024-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_clientmodel_address_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='date_of_birth_principal',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения доверителя'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='date_of_issued_principal',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выдачи доверителя'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='date_proxy',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата доверенности'),
        ),
    ]
