# Generated by Django 4.2.5 on 2024-12-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_clientmodel_date_of_birth_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='fio_principal',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='gender_principal',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default=None, max_length=1, null=True, verbose_name='Пол доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='is_principal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='name_principal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Имя доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='patronymic_principal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Отчество доверителя'),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='surname_principal',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Фамилия доверителя'),
        ),
    ]
